name: Publish Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Chart.yaml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.FILE_SYNC_PAT }}
          IS_FINE_GRAINED: true
          PR_LABELS: |
            file-sync
            automerge